services:
  # Postgres DB Service (for local development)
  database:
    image: postgres:16-alpine
    container_name: labos-database
    hostname: labos-database
    restart: always
    ports:
      - '${DB_FORWARD_PORT:-${DATABASE_PORT:-5432}}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      labos-network:
        aliases:
          - labos-database

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: labos-pgadmin
    restart: always
    ports:
      - '${PGADMIN_FORWARD_PORT:-8888}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - labos-network

  # NestJS Backend Service
  backend:
    container_name: labos-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - '${APP_FORWARD_PORT:-${PORT:-8080}}:${PORT:-8080}'
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - labos-network
    restart: on-failure
    tty: true
    stdin_open: true
    command: npm run start:dev
    expose:
      - '${PORT:-8080}'
networks:
  labos-network:
    name: labos-network
    driver: bridge

volumes:
  pg_data: {}
  pgadmin_data: {}
